### ISSUE TITLE
feature request : “Relative Bearing to Anchor” 

### ISSUE THREAD

**Issue by gregsyoung** [sbender9/signalk-anchoralarm-plugin#17]
Feature request :   
when retrieving anchor - it would be useful to have a simple “relative bearing to anchor” 
(also useful when at anchor without needing to look at mfd chart ) 

Background …. 
i typically anchor single handed - doing it whilst at the bow (with remote control for engine & thruster etc) ..
but a long way from an mfd or tablet that can show chart with boat position & anchor waypoint etc …

im using an “old” smartphone (android) with KIP display - that provides large readout of 
depth, anchor rode out, distance to anchor;
and would be useful to add “bearing to anchor” as the final peice of critical info.

I use WilhelmSK (just love it! fantastic!) ….. but dont fancy taking my IPAD to the bow …
and i dont have a suitable “old” iphone that i consider “disposable” for bow anchoring duties ..

i put the smartphone in a waterproof armband pouch … and with its large (KIP) display, at a glance i
can see what i need, whilst having both hands free for remote control .. and “hanging on” .. when needed!

**Comment by gregsyoung** [comment]
fantasticaly fast response,
new functionality working well. 
thanks again for responding

suggestion : for users with a simple text type display, it would be useful to have a
apparent bearing to anchor .... with indication of Port or Starboard and angle (positive)
eg Port 38

**Comment by Ric121** [comment]
Sorry, I don't see a bearing field in the interface. Am I missing something? And what is "Altitude"?

I'm on the same situation as Greg (Sigle handled)
Actually I think that "Bearing to Anchor" is better than Relative Bearing to the bow. Because the boat is rarely aligned with the anchor (because of the wind pushing the freeboard). I put a tripping ligne often and it's very easy to take a bearing to the anchor and set up that way.

**Comment by gregsyoung** [comment]
when anchor alarm is set … 
i see paths
navigation.anchor.apparentBearing.   (this can be positive or negative… as its a relative ebaring to bow)
navigation.anchor.bearingTrue. (similar to above but its a true bearing not relative)
navigation.anchor.position  (lat and long) … but nothing about “altitude ” ??

.. not sure i cn reconcile your comments/observations

- imho, when im at the bow, lifting anchor, the relative bering (to bow) is the msot relevant.. as it tells me where the anchor
- is in relation to my bow (direction) …. true bearing gets confusing .. as u need to determine your heading etc 
no idea where the “altitude” you mention ismshown?

**Comment by Ric121** [comment]
![Screenshot from 2023-10-04 15-41-12](https://github.com/sbender9/signalk-anchoralarm-plugin/assets/62102028/afc659f0-a542-444d-b55f-491f09ae1246)
I attach a screenshot of the pluggin settings. I don't see "bearing" anywhere, and there is a fied named "alltitude" In the Anchor Postion section.

---
Well I do differently: when I drop the anchor I don't want to deal with computer things. 
I set up the Anchor Watch once itś done and I have checked the anchor snorkling. If I use a tripping line I know perfectly where the anchor is and with a handbearing compas (mandatory on board), I have a remarkly precise solution. If I don't use a tripping line, I ask someone to take the bearing when I check it snorkling. If I'm alone, no tripping line, nobody to help and no snorkling, I just stretch the chain with the engine and take the bearing of the bow.
 I was doing as you say before using Angle to the bow but it is nothing close in precision than my new method.
"Bearing to Anchor" is also used in the popular app AnchorPro, Anchor Lite etc.

Then in openCPN using the Ruller, you can drop a mark very easily with bearing/distance. The problem with openCPN alarm is that it cannot be transformed in signal-k notification. That's why I was trying the pluggin.

**Comment by gregsyoung** [comment]
the paths and respective values are the output of the plugin, you can see them via data browser in the signalk web gui.

**Comment by Ric121** [comment]
Sorry I don't understand. What is the interface I show on the screenshot made for?

**Comment by gregsyoung** [comment]
that is the plugin config page
.. in the webapp tab, you will find link to anchor alarm ..  note that there are multiple ways
to display and control anchor alarm plugin.
the above link, wilhelmsk, freeboard etc

the bearing (& other data)  i mentioned is a signalk path, that can then be displayed using one of these apps.

**Comment by Ric121** [comment]
OK, got it. sorry for the confusion. I thought Bearing was an input. Altitude remains weird to me but maybe it's something related to tide height.... Thanks a lot.
(PS: I'm still not sure how I can set the anchor if I don't do it at the very moment of anchor drop - and even like that it depends from the distance from the GPS to the bow. How do people do exactly when they want to set up an anchor watch after the boat has anchored?)

**Comment by gregsyoung** [comment]
yes set anchor watch at time of drop is best, then fine tune anchor position based on observing swing radius and rode deployed.
because im single handed… there are 2 techniques ive used.
- have tracks on mfd enabled… its usualy possible to see the boat movement from moving fwd/maneouvering… and then reversing/falling back during the drop…. pick the obvious drop point … get coords from mfd. then enter into anchor alarm.
- ive now refined my system … and ingest chain counter and windlass /direction into signalk … via custom circuitry and sensesp.
using some nodred logic, i set the anchor alarm automatically when chain is going out, and it exceeds a calculated threshold. 
ie the anchor is dropping…
this works quite well as it uses boat gps positioning etc. (yes you need to ensure you have the gps offset to bow correctly setup also)
… and always check the visual track/radius against the alarm circle… and fine tune anchor position if needed.

**Comment by Ric121** [comment]
If you have automated it, it's another story. I'm single handled too and I keep thinking playing with the software at the moment of anchor drop is not a good option for me. But once the anchor is droped and all setlled, there is no easy solution. Anyway it's probably not the right place for this debate ;-). I will submit a request enhancement if you don't mind.
